language: node_js
node_js:
  - "10"

script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run build:demo; fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: gh-pages
  target-branch: gh-pages
  on:
    branch: master